### ISSUE TITLE
Общая задача для создания нового сайта

### ISSUE THREAD

**Issue by fogrew** [web-standards-ru/new#1]
**Миссия:**
Нужно собрать существующий контент в одно место - сайт. Он выступит парсером других репозиториев в группе web-standard-ru

**TODO:**
Нужно в отдельном репозитории создать механизм для автоматической генерации нового сайта из статики в разных репозиториях. Также в формате markdown.

За основу возьмём [старый сайт](https://web-standards.ru/).

Для каждого проекта нужно создать лендинг,
плюс страницы для уровней разделов проектов:

<h2 id="sections">Разделы</h2>

* [x] Статьи с существующего сайта (2.0.0)
  * [x] сконвертировать старые статьи html в md
  * новости и прочие разделы - потом
* [x] Весь контент с медиума (2.0.0)
  * [x] сконвертировать разово в md, затем отправлять на медиум из гитхаба
* [ ] Спроектировать дизайн #20 
  * [ ] статьи
  * [ ] календарь
* [ ] Сверстать по дизайну #21 
  * [ ] статьи
  * [ ] календарь
* [x] Календарь событий с гитхаба (2.0.0) (Задача #14)
* [ ] [Конференции WSD](wsd.events) (2.1.0)
  * [ ] сконвертировать в md из html
  * [ ] добавить разделы годов и месяцев
* [ ] Подкасты (2.1.0)
  * [ ] страницу и тег audio на каждый подкаст
* [ ] Карта cityjs (2.2.0)
* [ ] Словарь по фронтенду (2.3.0)

- [x] Пригласить всех на гитхабе
- [x] Положить в публичную папку Google Drive текущий контент (стиль, дизайны)
- [x] Продумать карту сайта (@pepelsbey)

Делаем итеративно.
Ориентируемся, что сделаем версию 2.0.0 примерно к концу октября.

**Comment by pepelsbey** [comment]
Пока закрываю, раз процессы вылетели в окно.
